# Pytorch: Warm-up

We hope you have had time to look at the [Prerequisites/Python-05-PyTorch](https://github.com/drinkingkazu/slacml-kmi2020/blob/master/Prerequisites/Python-05-PyTorch.ipynb) example to learn about `Pytorch`, a neural network library we use in this workshop. This notebook is to revisit the similar contents to ensure we cover the basics before playing with more complicated examples. In fact, we will simply make the same contents into exercises :)


In [1]:
from __future__ import print_function
import numpy as np
import torch
SEED=123
np.random.seed(SEED)
torch.manual_seed(SEED)
import matplotlib.pyplot as plt
%matplotlib inline

## Exercise 1 - data types

1. Create a `torch.Tensor` of a shape (3,2) filled with zeros, ones, and also random values sampled from a normal distribution (0 mean 1 std).
2. Create a `torch.Tensor` of a shape (10,10) filled with zeros except for the diagonal elements with ones. Compute the mean and std of the elements.
3. Reshape the tensor from step 2 into (1,1,10,10)
4. Repeat the step 2 to compute the mean and std, but use 8 byte (64 bit, double precision) floating point.
5. Slice the diagonal element of the 2D tensor from step 4.

In [2]:
# Step 1 ... Tensor of 0s = numpy.zeros
t=torch.zeros(3,2)
print('torch.zeros:\n',t)

# Step 1 ... Tensor of 1s = numpy.ones
t=torch.ones(3,2)
print('\ntorch.ones:\n',t)

# Step 1 ... Normal distribution centered at 0.0 and sigma=1.0 = numpy.rand.randn
t=torch.randn(3,2)
print('\ntorch.randn:\n',t)

# Step 2 ... Identity matrix
t=torch.eye(10)
print('\nidentity matrix:\n',t)
print('\nmean',t.mean().item(),'std',t.std().item())

# Step 3 ... reshaping
print('\nReshaped',t.reshape(1,1,*tuple(t.shape)).shape)

# Step 4 ... Double precision
t=torch.eye(10,dtype=torch.float64)
print('\n64 bit mean',t.mean().item(),'std',t.std().item())

# Step 5 ... Slicing
print('\nThe diagonal slice',t[t>0])

torch.zeros:
 tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

torch.ones:
 tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

torch.randn:
 tensor([[-0.1115,  0.1204],
        [-0.3696, -0.2404],
        [-1.1969,  0.2093]])

identity matrix:
 tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

mean 0.10000000149011612 std 0.30151134729385376

Reshaped torch.Size([1, 1, 10, 10])

64 bit mean 0.1 std 0.3015113445777634

The diagonal slice tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64)


<a href="dataloader"></a>
## Exercise 2 - dataloader

In [3]:
class dataset:
    
    def __init__(self):
        self._data = tuple(range(100))
        
    def __len__(self):
        return len(self._data)
    
    def __getitem__(self,index):
        return self._data[index]
    
data = dataset()

1. Construct a data loader with batch size 10 and enable random shuffling.
2. Loop over 20 iterations. Print the batch data in each loop.
3. After 10 iterations, was there any duplicate data entry?

In [4]:
from torch.utils.data import DataLoader
loader = DataLoader(data,batch_size=10,shuffle=True,num_workers=1)
ctr = 0
while ctr<20:
    for batch_data in loader:
        print('Iteration',ctr,'batch data',batch_data)
        ctr += 1
        
# check data unique count after 10 iterations
data_collection = []
for batch_data in loader:
    data_collection.append(batch_data.numpy())
    
print('\nunique data element count:',len(np.unique(np.concatenate(data_collection))))

Iteration 0 batch data tensor([12, 22, 48, 77,  3, 65, 26, 47, 99, 43])
Iteration 1 batch data tensor([89, 90, 25, 61, 20, 41, 52, 27,  0, 35])
Iteration 2 batch data tensor([54, 67, 45, 78, 72,  1, 14, 83, 44, 80])
Iteration 3 batch data tensor([ 9, 98, 24, 95, 70, 23, 69, 75, 29,  2])
Iteration 4 batch data tensor([91, 55,  5, 71, 68, 38, 31, 92, 39,  4])
Iteration 5 batch data tensor([74, 17, 94, 62, 79, 49,  7, 76, 15, 28])
Iteration 6 batch data tensor([42, 10, 59, 86, 50, 16, 97, 57, 84, 63])
Iteration 7 batch data tensor([96, 66, 18, 46, 13, 88, 40, 53, 33, 81])
Iteration 8 batch data tensor([85, 36, 87, 58, 37, 11, 30, 73, 32, 93])
Iteration 9 batch data tensor([21, 19, 34, 82,  8, 60, 56,  6, 51, 64])
Iteration 10 batch data tensor([43, 96,  9, 21, 75, 99,  6, 81, 27, 31])
Iteration 11 batch data tensor([65, 51, 34, 92,  0, 97, 66, 68, 53, 32])
Iteration 12 batch data tensor([58, 57, 88, 12, 94, 29, 87, 19, 62, 48])
Iteration 13 batch data tensor([30, 95, 85, 16, 91, 73, 41, 6

<a href="graph"></a>
## Exercise 3 - Pytorch `nn` modules

In the prerequisites, you have seen a few `nn` modules. Let's review them:

* `torch.nn.ReLU` ([link](https://pytorch.org/docs/stable/generated/torch.nn.ReLU.html#torch.nn.ReLU)) ... a function that takes an input tenor and outputs a tensor of the same shape where elements are 0 if the corresponding input element has a value below 0, and otherwise the same value.
* `torch.nn.Softmax` ([link](https://pytorch.org/docs/stable/generated/torch.nn.Softmax.html#torch.nn.Softmax)) ... a function that applies a [softmax function](https://en.wikipedia.org/wiki/Softmax_function) on the specified dimension of an input data.
* `torch.nn.MaxPool2d` ([link](https://pytorch.org/docs/stable/generated/torch.nn.MaxPool2d.html#torch.nn.MaxPool2d)) ... a function that down-sample the input matrix by taking maximum value from sub-matrices of a specified shape.

We introduce another module, a linear model
* `torch.nn.Linear` ([link](https://pytorch.org/docs/stable/generated/torch.nn.Linear.html#torch.nn.Linear) ... a module that can implement multiple linear models (i.e. $\vec{w}\cdot\vec{x}+b$).

In [5]:
torch.manual_seed(123)
model = torch.nn.Linear(in_features=1,out_features=1,bias=True)
print('\nWeights',model.weight)
print('\nBias',model.bias)

# Try multiplying 0
data = torch.Tensor([0.])
print('\nWith input (0) ...', model(data).item())

# Try multiplying 1
data = torch.Tensor([1.])
print('\nWith input (1) ...', model(data).item())

# Try 10 input data points
data = torch.Tensor([1.]*10).reshape(10,1)
print('\nWith input (1,...1)',model(data).detach().numpy())


Weights Parameter containing:
tensor([[-0.4078]], requires_grad=True)

Bias Parameter containing:
tensor([0.0331], requires_grad=True)

With input (0) ... 0.033124566078186035

With input (1) ... -0.37465155124664307

With input (1,...1) [[-0.37465155]
 [-0.37465155]
 [-0.37465155]
 [-0.37465155]
 [-0.37465155]
 [-0.37465155]
 [-0.37465155]
 [-0.37465155]
 [-0.37465155]
 [-0.37465155]]



Suppose we have 2 data points where each data point is represented by a 2D matrix of 5x6 filled with values sampled from a normal distribution

In [6]:
# Create a 2D tensor of shape (1,5,5) with some negative and positive values
torch.manual_seed(123)
data = torch.randn(60).reshape(2,5,6)
data

tensor([[[ 0.3374, -0.1778, -0.3035, -0.5880,  0.3486,  0.6603],
         [-0.2196, -0.3792,  0.7671, -1.1925,  0.6984, -1.4097],
         [ 0.1794,  1.8951,  0.4954,  0.2692, -0.0770, -1.0205],
         [-0.1690,  0.9178,  1.5810,  1.3010,  1.2753, -0.2010],
         [ 0.4965, -1.5723,  0.9666, -1.1481, -1.1589,  0.3255]],

        [[-0.6315, -2.8400, -1.3250,  0.1784, -2.1338,  1.0524],
         [-0.3885, -0.9343, -0.4991, -1.0867,  0.8805,  1.5542],
         [ 0.6266, -0.1755,  1.3111, -0.2199,  0.2190,  0.2045],
         [ 0.5146,  0.9938, -0.2587, -1.0826,  0.1036, -2.1996],
         [-0.0885, -0.5612,  0.6716,  0.6933, -0.9487, -0.0765]]])


Suppose we apply 
1. `ReLU`
2. `Softmax` across `dim=2`
3. `MaxPool2d` with `kernel_size=(1,3)`
4. `flatten`

* What is the shape of the output tensor?
* Implement above operations.
* Reshape the output of the last step so that it can be consumed by `Linear` module of `in_features=5` and `out_features=1`.
* Write a torch module (class) that performs a simple operation of "multiply 10" to the input tensor.
* Implement all modules into a `torch.nn.Sequential` container.

In [7]:
torch.manual_seed(123)

# Implement steps 1 to 5
op1 = torch.nn.ReLU()
op2 = torch.nn.Softmax(dim=2)
op3 = torch.nn.MaxPool2d(kernel_size=(1,3))

flattened = torch.flatten(op3(op2(op1(data))))
print('Shape of the output after flatten', flattened.shape)

# We need to reshape so that the data has 5 features
op4 = torch.nn.Linear(in_features=5,out_features=1)
print('Linear layer output',op4(flattened.reshape(-1,5)))

# module to multiply 10

class MyOp(torch.nn.Module):
        
    def __init__(self,linear_op):
        super().__init__()
        self.linear = linear_op
        
    def forward(self,data):
        return self.linear(torch.flatten(data).reshape(-1,5)) * 10
    
op5 = MyOp(op4)
op_all = torch.nn.Sequential(op1,op2,op3,op5)
print(op_all(data))

Shape of the output after flatten torch.Size([20])
Linear layer output tensor([[0.0834],
        [0.2547],
        [0.2215],
        [0.2266]], grad_fn=<AddmmBackward>)
tensor([[0.8344],
        [2.5468],
        [2.2151],
        [2.2662]], grad_fn=<MulBackward0>)
